branch-defaults:
  awsdeploy:
    environment: qwerty
    group_suffix: null
  master:
    environment: null
    group_suffix: null
environment-defaults:
  publichatroom:
    branch: null
    repository: null
  qwerty:
    branch: awsdeploy
    repository: chatroom
global:
  application_name: chatroom-aws5
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
